---
title: "Asian Art Museum - Google Analytics metrics"
author: "Diego Enriquez"
date: "9/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE}
suppressMessages(library(data.table))
suppressMessages(library(lubridate))
suppressMessages(library(ggplot2))
suppressMessages(library(grid))

# Functions ==================================================================================================================================
source("asianart_func.R")
```

```{r echo=FALSE, warning=FALSE}
ga_allws_nochn_all <- readQueryExplorerData("data/ga/asian_allws_nochn_all.tsv", c("Date"))
ga_allws_nochn_os <- readQueryExplorerData("data/ga/asian_allws_nochn_os.tsv", c("Date"))
ga_allws_nochn_us <- readQueryExplorerData("data/ga/asian_allws_nochn_us.tsv", c("Date"))
ga_allws_nochn_do <- readQueryExplorerData("data/ga/asian_allws_nochn_do.tsv", c("Date"))
ga_allws_nochn_lo <- readQueryExplorerData("data/ga/asian_allws_nochn_lo.tsv", c("Date"))

ga_allws_chn_all <- readQueryExplorerData("data/ga/asian_allws_chn_all.tsv", c("Date", "Channel"))
ga_allws_chn_os <- readQueryExplorerData("data/ga/asian_allws_chn_os.tsv", c("Date", "Channel"))
ga_allws_chn_us <- readQueryExplorerData("data/ga/asian_allws_chn_us.tsv", c("Date", "Channel"))
ga_allws_chn_do <- readQueryExplorerData("data/ga/asian_allws_chn_do.tsv", c("Date", "Channel"))
ga_allws_chn_lo <- readQueryExplorerData("data/ga/asian_allws_chn_lo.tsv", c("Date", "Channel"))

ga_plan_nochn_all <- readQueryExplorerData("data/ga/asian_plan_nochn_all.tsv", c("Date"))
ga_plan_nochn_os <- readQueryExplorerData("data/ga/asian_plan_nochn_os.tsv", c("Date"))
ga_plan_nochn_us <- readQueryExplorerData("data/ga/asian_plan_nochn_us.tsv", c("Date"))
ga_plan_nochn_do <- readQueryExplorerData("data/ga/asian_plan_nochn_do.tsv", c("Date"))
ga_plan_nochn_lo <- readQueryExplorerData("data/ga/asian_plan_nochn_lo.tsv", c("Date"))

ga_plan_chn_all <- readQueryExplorerData("data/ga/asian_plan_chn_all.tsv", c("Date", "Channel"))
ga_plan_chn_os <- readQueryExplorerData("data/ga/asian_plan_chn_os.tsv", c("Date", "Channel"))
ga_plan_chn_us <- readQueryExplorerData("data/ga/asian_plan_chn_us.tsv", c("Date", "Channel"))
ga_plan_chn_do <- readQueryExplorerData("data/ga/asian_plan_chn_do.tsv", c("Date", "Channel"))
ga_plan_chn_lo <- readQueryExplorerData("data/ga/asian_plan_chn_lo.tsv", c("Date", "Channel"))

ga_tickets_nochn_all <- readQueryExplorerData("data/ga/asian_tickets_nochn_all.tsv", c("Date"))
ga_tickets_nochn_os <- readQueryExplorerData("data/ga/asian_tickets_nochn_os.tsv", c("Date"))
ga_tickets_nochn_us <- readQueryExplorerData("data/ga/asian_tickets_nochn_us.tsv", c("Date"))
ga_tickets_nochn_do <- readQueryExplorerData("data/ga/asian_tickets_nochn_do.tsv", c("Date"))
ga_tickets_nochn_lo <- readQueryExplorerData("data/ga/asian_tickets_nochn_lo.tsv", c("Date"))

ga_tickets_chn_all <- readQueryExplorerData("data/ga/asian_tickets_chn_all.tsv", c("Date", "Channel"))
ga_tickets_chn_os <- readQueryExplorerData("data/ga/asian_tickets_chn_os.tsv", c("Date", "Channel"))
ga_tickets_chn_us <- readQueryExplorerData("data/ga/asian_tickets_chn_us.tsv", c("Date", "Channel"))
ga_tickets_chn_do <- readQueryExplorerData("data/ga/asian_tickets_chn_do.tsv", c("Date", "Channel"))
ga_tickets_chn_lo <- readQueryExplorerData("data/ga/asian_tickets_chn_lo.tsv", c("Date", "Channel"))

ga_visit_nochn_all <- readQueryExplorerData("data/ga/asian_visit_nochn_all.tsv", c("Date"))
ga_visit_nochn_os <- readQueryExplorerData("data/ga/asian_visit_nochn_os.tsv", c("Date"))
ga_visit_nochn_us <- readQueryExplorerData("data/ga/asian_visit_nochn_us.tsv", c("Date"))
ga_visit_nochn_do <- readQueryExplorerData("data/ga/asian_visit_nochn_do.tsv", c("Date"))
ga_visit_nochn_lo <- readQueryExplorerData("data/ga/asian_visit_nochn_lo.tsv", c("Date"))

ga_visit_chn_all <- readQueryExplorerData("data/ga/asian_visit_chn_all.tsv", c("Date", "Channel"))
ga_visit_chn_os <- readQueryExplorerData("data/ga/asian_visit_chn_os.tsv", c("Date", "Channel"))
ga_visit_chn_us <- readQueryExplorerData("data/ga/asian_visit_chn_us.tsv", c("Date", "Channel"))
ga_visit_chn_do <- readQueryExplorerData("data/ga/asian_visit_chn_do.tsv", c("Date", "Channel"))
ga_visit_chn_lo <- readQueryExplorerData("data/ga/asian_visit_chn_lo.tsv", c("Date", "Channel"))

daysinfo <- data.table(Date = seq(as.Date("2016-01-01"), as.Date("2018-06-30"), by = "day"))
daysinfo$weekNum <- wday(daysinfo$Date, week_start = 1)
daysinfo$isFirstSunday <- wday(daysinfo$Date, week_start = 1) == 7 & day(daysinfo$Date) <= 7
```

## All Web Site

### All locations

```{r ga_allws_nochn_all, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_all, limitDates = c("2016-07-06", "2018-06-30"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Overseas

```{r ga_allws_nochn_os, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_os, limitDates = c("2016-07-06", "2018-06-30"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### United States

```{r ga_allws_nochn_us, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_us, limitDates = c("2016-07-06", "2018-06-30"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Domestics

```{r ga_allws_nochn_do, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_do, limitDates = c("2016-07-06", "2018-06-30"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Locals

```{r ga_allws_nochn_lo, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_lo, limitDates = c("2016-07-06", "2018-06-30"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Channels

```{r ga_allws_chn_all, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_chn_all[Channel == "Organic Search"], limitDates = c("2016-07-06", "2018-06-30"))
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```
